{{- if .Values.pvc.create -}}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
 name: django-server-pvc
spec:
 storageClassName: {{ .Values.pvc.storageClassName }}
 accessModes:
   - {{ .Values.pvc.accessModes }}
 resources:
   requests:
     storage: {{ .Values.pvc.size }}
{{- end -}}